flower_puzzle = {
    { name = "牡丹",verse = "任是无情也动人"},
    { name = "梅花",verse = "竹篱茅舍自甘心"},
    { name = "海棠",verse = "只恐夜深花睡去"},
    { name = "并蒂",verse = "连理枝头花正开"},
    { name = "梨花",verse = "惆怅东栏一株雪"},
    { name = "栀子",verse = "薝卜香清水影寒"},
    { name = "水仙",verse = "不是人间富贵妆"},
    { name = "兰花",verse = "名在山林处士家"},
    { name = "芍药",verse = "自是风流时世妆"},
    { name = "桂花",verse = "人与花心各自香"},
    { name = "杜鹃",verse = "花花叶叶正含芳"},
    { name = "菊花",verse = "此花开尽更无花"},
    { name = "丽春",verse = "花开更比杜鹃红"},
    { name = "山茶",verse = "细雨无人我独来"},
    { name = "石竹",verse = "买却春风是此花"},
    { name = "紫薇",verse = "向风偏笑艳阳人"},
    { name = "玉兰",verse = "隔帘轻解白霓裳"},
    { name = "玉簪",verse = "雪魄冰姿俗不侵"},
    { name = "蔷薇",verse = "总是输君浅淡妆"},
    { name = "玫瑰",verse = "一花两色浅深红"},
    { name = "茉莉",verse = "沈水熏成换骨香"},
    { name = "丁香",verse = "冷垂串串玲珑雪"},
    { name = "含笑",verse = "无人知处自然香"},
}